backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "/" # Media files will be stored in the repo under /
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
